name: pypi-publish
on:
  push:
    branches:
      - main
jobs:
    pypi-publish:
      name: upload release to PyPI
      runs-on: ubuntu-latest
      environment: 
        name: pypi-release
      permissions:
        # IMPORTANT: this permission is mandatory for trusted publishing
        id-token: write
      steps:
        # retrieve your distributions here
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v3
        - run: python -m pip install --upgrade build
        - run: python -m build
        - name: Publish package distributions to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
